--[[


Extra information

Do note that whatever the projects this module is placed into, the following modules will not be affected under the copyright or licences:
- t
- ProfileStore / Your own custom dataStore (module/wrapper) / others' dataStore wrapper/module.


---


Licence / Copyright information

MIT License

Copyright (c) 2026 "I accidentally polarized my pulsar star" -- Fish girl

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.


This module is under MIT licence.

---

=======
Module information

=> Creator: moyaiedStatue (stone) -- Roblox
			      "I accidentally polarized my pulsar star" -- Fish girl -- Github

=> Creation time:  10/05/2026 (DD/MM/YYYY)
=> Contains:
          dataModule.luau
          >  shared (Folder): DataSystemReportModule.luau
							                ProfileStore.luau
							                t.luau
        	>  extraInformation.luau (Disabled script)
        	>  APIModule.luau
        	>  TemplatesModule.luau
        	>  storeNameList.luau

Information ends
=======


]]
